name: 'HackMeNot Security Scanner'
description: 'AI-Era Code Security Scanner - find hardcoded secrets, vulnerabilities, and security issues'
author: 'HackMeNot'
branding:
  icon: 'shield'
  color: 'red'

inputs:
  path:
    description: 'Path to scan (file or directory)'
    required: false
    default: '.'
  severity:
    description: 'Minimum severity to report (critical, high, medium, low)'
    required: false
    default: 'low'
  fail-on:
    description: 'Minimum severity to fail the build (critical, high, medium, low)'
    required: false
    default: 'high'
  format:
    description: 'Output format (terminal, json, sarif)'
    required: false
    default: 'terminal'
  sarif-upload:
    description: 'Upload SARIF to GitHub Security tab'
    required: false
    default: 'false'
  changed-only:
    description: 'Only scan files changed in PR (uses --changed-since)'
    required: false
    default: 'false'
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'

outputs:
  findings-count:
    description: 'Number of findings detected'
    value: ${{ steps.scan.outputs.findings-count }}
  sarif-file:
    description: 'Path to SARIF file (if format=sarif)'
    value: ${{ steps.scan.outputs.sarif-file }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install hackmenot
      shell: bash
      run: pip install hackmenot

    - name: Determine base ref for changed-only
      id: base-ref
      if: inputs.changed-only == 'true'
      shell: bash
      run: |
        BASE_SHA="${{ github.event.pull_request.base.sha }}"
        if [ -n "$BASE_SHA" ]; then
          echo "ref=$BASE_SHA" >> $GITHUB_OUTPUT
        else
          echo "ref=HEAD~1" >> $GITHUB_OUTPUT
        fi

    - name: Run security scan
      id: scan
      shell: bash
      run: |
        SCAN_PATH="${{ inputs.path }}"
        SEVERITY="${{ inputs.severity }}"
        FAIL_ON="${{ inputs.fail-on }}"
        FORMAT="${{ inputs.format }}"
        SARIF_UPLOAD="${{ inputs.sarif-upload }}"
        CHANGED_ONLY="${{ inputs.changed-only }}"
        BASE_REF="${{ steps.base-ref.outputs.ref }}"

        # Build command
        if [ "$FORMAT" == "sarif" ] || [ "$SARIF_UPLOAD" == "true" ]; then
          SARIF_FILE="${{ runner.temp }}/hackmenot-results.sarif"

          # Build args array
          SCAN_ARGS=("$SCAN_PATH" --severity "$SEVERITY" --fail-on "$FAIL_ON" --ci --format sarif)

          # Add changed-only if enabled
          if [ "$CHANGED_ONLY" == "true" ] && [ -n "$BASE_REF" ]; then
            SCAN_ARGS+=(--changed-since "$BASE_REF")
          fi

          # Capture exit code to respect fail-on setting
          set +e
          hackmenot scan "${SCAN_ARGS[@]}" > "$SARIF_FILE" 2>/dev/null
          SCAN_EXIT_CODE=$?
          set -e

          echo "sarif-file=$SARIF_FILE" >> $GITHUB_OUTPUT

          # Count findings from SARIF
          FINDINGS=$(cat "$SARIF_FILE" | python -c "import json,sys; d=json.load(sys.stdin); print(sum(len(r.get('results',[])) for r in d.get('runs',[])))" 2>/dev/null || echo "0")
          echo "findings-count=$FINDINGS" >> $GITHUB_OUTPUT

          # Show results in log
          cat "$SARIF_FILE"

          # Exit with captured code to respect fail-on setting
          exit $SCAN_EXIT_CODE
        else
          # Build args array
          SCAN_ARGS=("$SCAN_PATH" --severity "$SEVERITY" --fail-on "$FAIL_ON" --ci --format "$FORMAT")

          # Add changed-only if enabled
          if [ "$CHANGED_ONLY" == "true" ] && [ -n "$BASE_REF" ]; then
            SCAN_ARGS+=(--changed-since "$BASE_REF")
          fi

          hackmenot scan "${SCAN_ARGS[@]}"
        fi

    - name: Upload SARIF to GitHub Security
      if: inputs.sarif-upload == 'true' && steps.scan.outputs.sarif-file != ''
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif-file }}
