# GitLab CI template for hackmenot security scanning
#
# Usage: Include in your .gitlab-ci.yml:
#   include:
#     - remote: 'https://raw.githubusercontent.com/hackmenot/hackmenot/main/ci-templates/gitlab-ci.yml'
#
# Or copy the jobs you need into your pipeline.

# Main security scan job
hackmenot:
  image: python:3.11-slim
  stage: test
  variables:
    HACKMENOT_FAIL_ON: high
  before_script:
    - pip install --quiet hackmenot
  script:
    - hackmenot scan . --ci --fail-on $HACKMENOT_FAIL_ON --format sarif > gl-sast-report.json
  artifacts:
    reports:
      sast: gl-sast-report.json
    paths:
      - gl-sast-report.json
    when: always
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  allow_failure: false

# Optional: Post findings as MR comment
# Requires GITLAB_TOKEN variable with api scope
hackmenot:comment:
  image: python:3.11-slim
  stage: test
  needs: []
  variables:
    HACKMENOT_FAIL_ON: high
  before_script:
    - pip install --quiet hackmenot
  script:
    - hackmenot scan . --ci --pr-comment > comment.md
    - |
      if [ -s comment.md ] && [ -n "$GITLAB_TOKEN" ]; then
        apt-get update -qq && apt-get install -qq -y curl
        curl --fail --request POST \
          --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
          --form "body=<comment.md" \
          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}/notes"
      fi
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  allow_failure: true
